apiVersion: apps/v1
kind: Deployment
metadata:
  name: devworkspace-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: devworkspace-api
  template:
    metadata:
      labels:
        name: devworkspace-api
    spec:
      serviceAccountName: devworkspace-api
      containers:
        - name: devworkspace-api
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - devworkspace-api
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "devworkspace-api"
